export const ProfileData = {
  success: true,
  data: {
    accountTypeId: {
      id: 2,
      name: "Buyer",
    },
    activated: true,
    addressId: {
      addressLine: "Tamil Salai",
      billToCode: "123456",
      branchName: "BMC House",
      city: "Chennai",
      country: "India",
      countryCode: "IN",
      district: "Chennai",
      email: null,
      gst: "33COYPP2114N1ZE",
      id: 6673,
      isBilling: true,
      isCustAddress: false,
      isShipping: true,
      lattitude: "13.0722392",
      locality: "",
      locationUrl:
        "https://maps.google.com/?q=BMC+House&ftid=0x3a52660d31b3ee2b:0x98842f285b70774c",
      longitude: "80.25490359999999",
      mobileNo: "",
      nationalMobileNum: "91",
      phone: "",
      pinCodeId: "600008",
      primaryContact: "",
      regAddress: true,
      shipToCode: "123456",
      soldToCode: "123456",
      state: "Tamil Nadu",
      tenantId: 0,
      vendorID: null,
      vendorId: null,
      wareHouse: false,
    },
    bnplCustomerId: null,
    bnplEnabled: false,
    bnplPhone: null,
    businessTypeId: {
      id: 1089,
      name: "End User",
      tenantId: 0,
    },

    companyIdentifier: null,
    currencyId: {
      currencyCode: "INR",
      decimal: ".",
      description: "INDIAN RUPEE",
      id: 96,
      precision: 2,
      symbol: "INR ₹",
      tenantId: 0,
      thousand: ",",
    },
    defaultEmail: "madrastown18@gmail.com",
    finEndDate: null,
    finStartDate: null,
    finStartMonth: null,
    financialYear: null,
    id: 8690,
    inviteAccess: 0,
    logo: "https://schwingstetter-myapptino-assets.s3.ap-northeast-1.amazonaws.com/app_assets/company_images/8682/header/Schwing%20Place%20holder_1631123288548.png",
    name: "Blue Metals Company Pvt Ltd - Madrastown",
    profileAccess: true,
    reportEmail: null,
    subIndustryId: {
      description:
        "Manufacturers of civil or military aerospace & defence equipment, parts or products including electronics and space equipments",
      id: 3351,
      industryId: {
        id: 2208,
        name: "Aerospace & Defence",
        tenantId: 0,
      },
      name: "Aerospace & Defence",
      tenantId: 0,
    },
    taxDetailsId: {
      id: 242,
      pan: "123",
      panImage: null,
      tenantId: 0,
    },
    taxExempted: false,
    taxExemptionId: null,
    tenantId: 0,
    vendorId: null,
    verified: true,
    website: null,
  },
  isLoggedIn: true,
};

export default ProfileData;
