export const UserPrefrence = {
  success: true,
  data: {
    dateFormat: "17/09/2025",
    id: 12,
    tenantId: 0,
    timeFormat: "12 H",
    timeZone: "Asia/Kolkata",
    timeZoneOptions: [
      { value: "Asia/Kolkata", label: "Asia/Kolkata (GMT+05:30)" },
      { value: "America/New_York", label: "America/New_York (GMT-05:00)" },
      { value: "Europe/London", label: "Europe/London (GMT+00:00)" },
      { value: "Asia/Shanghai", label: "Asia/Shanghai (GMT+08:00)" },
    ],
    dateFormatOptions: [
      { value: "17/09/2025", label: "17/09/2025" },
      { value: "09/17/2025", label: "09/17/2025" },
      { value: "2025-09-17", label: "2025-09-17" },
      { value: "17-09-2025", label: "17-09-2025" },
    ],
    timeFormatOptions: [
      { value: "12H", label: "12-hour ()" },
      { value: "24H", label: "24-hour (HH:mm)" },
    ],
    userId: {
      cognitoName: null,
      createdOn: {
        dayOfMonth: 12,
        dayOfWeek: "THURSDAY",
        dayOfYear: 12,
        hour: 5,
        minute: 39,
        month: "JANUARY",
        monthValue: 1,
        nano: 0,
        second: 42,
        year: 2023,
      },
      department: "",
      displayName: "Narendran N",
      dottedReportingTo: null,
      email: "madrastown18@gmail.com",
      id: 1032,
      isActive: 1,
      isDeleted: null,
      jobTitle: "",
      lastLoginAt: "2025-09-16T04:39:32.308Z",
      mobileNo: "",
      name: "61faa081aa81ccb144f577f2",
      nationalMobileNum: "",
      password: " ",
      picture: null,
      reportingTo: null,
      status: "CONFIRMED",
      tenantId: 0,
      updatedOn: {
        dayOfMonth: 16,
        dayOfWeek: "TUESDAY",
        dayOfYear: 259,
        hour: 4,
        minute: 39,
        month: "SEPTEMBER",
        monthValue: 9,
        nano: 0,
        second: 32,
        year: 2025,
      },
      userCode: null,
      userRoles: {
        description: null,
        id: 685,
        roleId: {
          id: 229,
          ownerRole: null,
          roleDescription: "Admin",
          roleName: "Buyer Admin",
          tenantId: 0,
          vendorId: null,
        },
        tenantId: 0,
        vendorId: null,
      },
      usersCompanyMappings: {
        companyId: {
          accountTypeId: {
            id: 2,
            name: "Buyer",
          },
          activated: true,
          addressId: {
            addressLine: "Tamil Salai",
            billToCode: "123456",
            branchName: "BMC House",
            city: "Chennai",
            country: "India",
            countryCode: "IN",
            district: "Chennai",
            email: null,
            gst: "33COYPP2114N1ZE",
            id: 6673,
            isBilling: true,
            isCustAddress: false,
            isShipping: true,
            lattitude: "13.0722392",
            locality: "",
            locationUrl:
              "https://maps.google.com/?q=BMC+House&ftid=0x3a52660d31b3ee2b:0x98842f285b70774c",
            longitude: "80.25490359999999",
            mobileNo: "",
            nationalMobileNum: "91",
            phone: "",
            pinCodeId: "600008",
            primaryContact: "",
            regAddress: true,
            shipToCode: "123456",
            soldToCode: "123456",
            state: "Tamil Nadu",
            tenantId: 0,
            vendorID: null,
            vendorId: null,
            wareHouse: false,
          },
          bnplCustomerId: null,
          bnplEnabled: false,
          bnplPhone: null,
          businessTypeId: {
            id: 1089,
            name: "End User",
            tenantId: 0,
          },
          companyIdentifier: null,
          currencyId: {
            currencyCode: "INR",
            decimal: ".",
            description: "INDIAN RUPEE",
            id: 96,
            precision: 2,
            symbol: "INR ₹",
            tenantId: 0,
            thousand: ",",
          },
          defaultEmail: "madrastown18@gmail.com",
          finEndDate: null,
          finStartDate: null,
          finStartMonth: null,
          financialYear: null,
          id: 8690,
          inviteAccess: 0,
          logo: "https://schwingstetter-myapptino-assets.s3.ap-northeast-1.amazonaws.com/app_assets/company_images/8682/header/Schwing%20Place%20holder_1631123288548.png",
          name: "Blue Metals Company Pvt Ltd - Madrastown",
          profileAccess: true,
          reportEmail: null,
          subIndustryId: {
            description:
              "Manufacturers of civil or military aerospace & defence equipment, parts or products including electronics and space equipments",
            id: 3351,
            industryId: {
              id: 2208,
              name: "Aerospace & Defence",
              tenantId: 0,
            },
            name: "Aerospace & Defence",
            tenantId: 0,
          },
          taxDetailsId: {
            id: 242,
            pan: "123",
            panImage: null,
            tenantId: 0,
          },
          taxExempted: false,
          taxExemptionId: null,
          tenantId: 0,
          vendorId: null,
          verified: true,
          website: null,
        },
        id: 681,
        tenantId: 0,
        vendorId: null,
      },
      vendorId: null,
    },
    vendorId: null,
  },
};
export default UserPrefrence;
