import { ProductListItem } from "@/types/product-listing";

/**
 * Mock Product Data
 * Simplified version with only essential product information
 */
export const mockProducts: ProductListItem[] = [
  {
    id: 64175,
    sku: "P000038",
    title: "Milwaukee Clear High Performance Safety Glasses with Gasket Kit",
    brand: "Milwaukee",
    price: 17892, // $178.92 in cents
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "safety",
    subCategory: "eye-protection",
    color: "black",
  },
  {
    id: 64176,
    sku: "DW20055",
    title: "DeWalt 20V MAX Cordless Drill/Driver Kit with 2 Batteries",
    brand: "DeWalt",
    price: 14999, // $149.99
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "drills",
    color: "yellow",
  },
  {
    id: 64177,
    sku: "MK4350FCT",
    title: 'Makita 4-1/2" Angle Grinder with Case',
    brand: "Makita",
    price: 8995,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "power-tools",
    subCategory: "grinders",
    color: "blue",
  },
  {
    id: 64178,
    sku: "B12487",
    title: "Bosch 12-Inch Dual-Bevel Sliding Compound Miter Saw",
    brand: "Bosch",
    price: 59999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "saws",
    color: "blue",
  },
  {
    id: 64179,
    sku: "ST33725",
    title: "Stanley 25-Foot FatMax Tape Measure",
    brand: "Stanley",
    price: 1899,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "measuring",
    subCategory: "tape-measures",
    color: "yellow",
  },
  {
    id: 64180,
    sku: "ML48223",
    title: "Milwaukee M18 FUEL 18V Lithium-Ion Brushless Impact Driver",
    brand: "Milwaukee",
    price: 17999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "impact-drivers",
    color: "red",
  },
  {
    id: 64181,
    sku: "RY40250",
    title: "Ryobi 40V Brushless String Trimmer with Battery and Charger",
    brand: "Ryobi",
    price: 12999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "power-tools",
    subCategory: "outdoor",
    color: "green",
  },
  {
    id: 64182,
    sku: "KL32500",
    title: "Klein Tools Journeyman Leather Tool Belt",
    brand: "Klein Tools",
    price: 8499,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "storage",
    subCategory: "tool-belts",
    color: "black",
  },
  {
    id: 64183,
    sku: "3M91298",
    title: "3M WorkTunes Connect Hearing Protector with Bluetooth",
    brand: "3M",
    price: 5999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "safety",
    subCategory: "hearing-protection",
    color: "black",
  },
  {
    id: 64184,
    sku: "IR10505",
    title: "Irwin Quick-Grip One-Handed Bar Clamp 24-Inch",
    brand: "Irwin",
    price: 2499,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "hand-tools",
    subCategory: "clamps",
    color: "blue",
  },
  {
    id: 64185,
    sku: "CM26789",
    title: "Craftsman 230-Piece Mechanics Tool Set with Case",
    brand: "Craftsman",
    price: 19999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "hand-tools",
    subCategory: "tool-sets",
    color: "red",
  },
  {
    id: 64186,
    sku: "BD20045",
    title: "Black & Decker 20V MAX Cordless Jigsaw",
    brand: "Black & Decker",
    price: 6999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "power-tools",
    subCategory: "saws",
    color: "orange",
  },
  {
    id: 64187,
    sku: "ML49218",
    title: "Milwaukee 18V LED Work Light with Tripod",
    brand: "Milwaukee",
    price: 12999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "lighting",
    subCategory: "work-lights",
    color: "red",
  },
  {
    id: 64188,
    sku: "DW33456",
    title: "DeWalt ToughSystem 2.0 Tool Storage Box",
    brand: "DeWalt",
    price: 8999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "storage",
    subCategory: "tool-boxes",
    color: "yellow",
  },
  {
    id: 64189,
    sku: "MK55607",
    title: "Makita 10-Inch Compound Miter Saw",
    brand: "Makita",
    price: 34999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "power-tools",
    subCategory: "saws",
    color: "blue",
  },
  {
    id: 64190,
    sku: "B34521",
    title: "Bosch Laser Distance Measure 165 Feet",
    brand: "Bosch",
    price: 7999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: false,
    inStock: true,
    category: "measuring",
    subCategory: "laser-measures",
    color: "blue",
  },
  {
    id: 64191,
    sku: "P000039",
    title: "Milwaukee Anti-Fog Safety Glasses",
    brand: "Milwaukee",
    price: 1999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "safety",
    subCategory: "eye-protection",
    color: "black",
  },
  {
    id: 64192,
    sku: "DW20056",
    title: "DeWalt 20V MAX Cordless Impact Wrench",
    brand: "DeWalt",
    price: 22999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "impact-wrenches",
    color: "yellow",
  },
  {
    id: 64193,
    sku: "MK4351FCT",
    title: "Makita Cordless Circular Saw",
    brand: "Makita",
    price: 12999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "saws",
    color: "blue",
  },
  {
    id: 64194,
    sku: "B12488",
    title: "Bosch Cordless Drill Kit",
    brand: "Bosch",
    price: 15999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "drills",
    color: "blue",
  },
  {
    id: 64195,
    sku: "ST33726",
    title: "Stanley 30-Foot Tape Measure",
    brand: "Stanley",
    price: 2099,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "measuring",
    subCategory: "tape-measures",
    color: "yellow",
  },
  {
    id: 64196,
    sku: "ML48224",
    title: "Milwaukee M18 Cordless Grinder",
    brand: "Milwaukee",
    price: 19999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "grinders",
    color: "red",
  },
  {
    id: 64197,
    sku: "RY40251",
    title: "Ryobi Cordless Leaf Blower",
    brand: "Ryobi",
    price: 9999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "power-tools",
    subCategory: "outdoor",
    color: "green",
  },
  {
    id: 64198,
    sku: "KL32501",
    title: "Klein Tools Electrician Tool Set",
    brand: "Klein Tools",
    price: 11999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "storage",
    subCategory: "tool-sets",
    color: "black",
  },
  {
    id: 64199,
    sku: "3M91299",
    title: "3M Safety Helmet with Bluetooth",
    brand: "3M",
    price: 7999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "safety",
    subCategory: "head-protection",
    color: "black",
  },
  {
    id: 64200,
    sku: "IR10506",
    title: "Irwin Adjustable Wrench Set",
    brand: "Irwin",
    price: 2999,
    image: "https://placehold.co/600x400?text=Image",
    images: ["https://placehold.co/600x400?text=Image"],
    isNew: true,
    inStock: true,
    category: "hand-tools",
    subCategory: "wrenches",
    color: "blue",
  },
  // Add more products as needed for each category...
];

/**
 * Helper function to get products by category
 */
export function getProductsByCategory(categoryId: string): ProductListItem[] {
  if (categoryId === "all") {
    return mockProducts;
  }
  return mockProducts.filter(product => product.category === categoryId);
}

/**
 * Helper function to get products by brand
 */
export function getProductsByBrand(brandId: string): ProductListItem[] {
  return mockProducts.filter(
    product => product.brand.toLowerCase().replace(/\s+/g, "-") === brandId
  );
}
