import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import NavBar from "./Components/nav-bar";
import Footer from "./Components/footer";
import { I18nProvider } from "@/components/i18n-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   fallback: ['Arial', 'sans-serif']
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      // suppressHydrationWarning={true}
      >
        <I18nProvider>
          <NavBar />
          <AuthProvider>{children}</AuthProvider>
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
